before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: scraloud
    github:
      owner: scraloud
      name: homebrew-tap
    commit_author:
      name: musabgultekin
      email: musabgultekin@users.noreply.github.com
    folder: Formula
    caveats: "Just use scraloud"
    homepage: "https://scraloud.com/"
    description: "Deploy your scrapers to cloud and manage them easily."
    dependencies:
      - git
    test: |
      system "#{bin}/scraloud"
    install: |
      bin.install "scraloud"
